<a href="https://colab.research.google.com/github/duaanoor31/pandas-assignment/blob/main/pandas_core_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



> **Duaa Abdul Qadir**
**Roll No: 886550**

In [ ]:
import pandas as pd

In [ ]:
#Reading Data Set:
df = pd.read_csv("/Social_media_impact_on_life.csv")

print(df)

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
0     STU_2024000   19  Female  Undergraduate         Snapchat
1     STU_2024001   19  Female  Undergraduate        Instagram
2     STU_2024002   17  Female    High School           TikTok
3     STU_2024003   16  Female    High School          YouTube
4     STU_2024004   17    Male    High School         LinkedIn
...           ...  ...     ...            ...              ...
4495  STU_2028495   16    Male    High School          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4498  STU_2028498   16    Male    High School         LinkedIn
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone
1                   4.6                  1.3  Smartphone
2                  10.9                  1.7  Smartphone
3                   6.0                  2.3      Tablet
4                   3.3                  2.6  Smartphone
...                 ...                  ...         ...
4495                5.8                  1.2  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
0                      5.9                    2              True
1                      7.9                    3              True
2                      5.2                    1              True
3                      7.6                    4              True
4                      7.6                    4              True
...                    ...                  ...               ...
4495                   7.8                    3              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
0                         Always                    20.0                   73
1                      Sometimes                    17.0                   90
2                     Frequently                    18.0                   70
3                      Sometimes                    15.0                   82
4                          Never                    16.0                   84
...                          ...                     ...                  ...
4495                   Sometimes                    11.0                   79
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
0                         2.73        Neutral
1                         3.21     Beneficial
2                         3.00        Neutral
3                         3.42     Beneficial
4                         3.41     Beneficial
...                        ...            ...
4495                      2.85     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

[4500 rows x 16 columns]

In [ ]:
#Viewing Data:
df = pd.read_csv("/Social_media_impact_on_life.csv")
print(df.head(4))
print(df.tail(3))

    Student_ID  Age  Gender Academic_Level Primary_Platform  \
0  STU_2024000   19  Female  Undergraduate         Snapchat
1  STU_2024001   19  Female  Undergraduate        Instagram
2  STU_2024002   17  Female    High School           TikTok
3  STU_2024003   16  Female    High School          YouTube

   Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  Sleep_Duration_Hours  \
0                7.5                  1.5  Smartphone                   5.9
1                4.6                  1.3  Smartphone                   7.9
2               10.9                  1.7  Smartphone                   5.2
3                6.0                  2.3      Tablet                   7.6

   Sleep_Quality_Score  Late_Night_Usage Social_Comparison_Frequency  \
0                    2              True                      Always
1                    3              True                   Sometimes
2                    1              True                  Frequently
3                    4              True                   Sometimes

   Perceived_Stress_Score  Mental_Health_Index  Academic_Performance_GPA  \
0                    20.0                   73                      2.73
1                    17.0                   90                      3.21
2                    18.0                   70                      3.00
3                    15.0                   82                      3.42

  Overall_Impact
0        Neutral
1     Beneficial
2        Neutral
3     Beneficial
       Student_ID  Age Gender Academic_Level Primary_Platform  \
4497  STU_2028497   19   Male  Undergraduate        Instagram
4498  STU_2028498   16   Male    High School         LinkedIn
4499  STU_2028499   24   Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

In [ ]:
#Shape and Basic Properties:
df.shape

(4500, 16)

In [ ]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Primary_Platform',
       'Daily_Usage_Hours', 'Weekend_Extra_Hours', 'Device_Type',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Late_Night_Usage',
       'Social_Comparison_Frequency', 'Perceived_Stress_Score',
       'Mental_Health_Index', 'Academic_Performance_GPA', 'Overall_Impact'],
      dtype='object')

In [ ]:
df.dtypes

Student_ID                      object
Age                              int64
Gender                          object
Academic_Level                  object
Primary_Platform                object
Daily_Usage_Hours              float64
Weekend_Extra_Hours            float64
Device_Type                     object
Sleep_Duration_Hours           float64
Sleep_Quality_Score              int64
Late_Night_Usage                  bool
Social_Comparison_Frequency     object
Perceived_Stress_Score         float64
Mental_Health_Index              int64
Academic_Performance_GPA       float64
Overall_Impact                  object
dtype: object

In [ ]:
#Data Frame Information:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   object
 1   Age                          4500 non-null   int64
 2   Gender                       4500 non-null   object
 3   Academic_Level               4500 non-null   object
 4   Primary_Platform             4500 non-null   object
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   object
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   object
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   object
dtypes: bool(1), float64(5), int64(3), object(7)
memory usage: 531.9+ KB

In [ ]:
#Statistical Summary:
df.describe()

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4454.000000,4500.000000,4415.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.072859,12.876044,0.392662
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.460000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [ ]:
# selecting Columns:
df['Academic_Level']

0       Undergraduate
1       Undergraduate
2         High School
3         High School
4         High School
            ...
4495      High School
4496    Undergraduate
4497    Undergraduate
4498      High School
4499    Undergraduate
Name: Academic_Level, Length: 4500, dtype: object

In [ ]:
#Selecting Multiple Columns:
df[["Gender","Sleep_Duration_Hours"]]

      Gender  Sleep_Duration_Hours
0     Female                   5.9
1     Female                   7.9
2     Female                   5.2
3     Female                   7.6
4       Male                   7.6
...      ...                   ...
4495    Male                   7.8
4496  Female                   6.6
4497    Male                   6.0
4498    Male                   7.1
4499    Male                   6.8

[4500 rows x 2 columns]

In [ ]:
# Selecting Rows — loc and ilo
(df.loc[4495, "Academic_Level"])

'High School'

In [ ]:
print(df.iloc[4497, 14])

3.16

In [ ]:
#Filtering Data :
high_usage = df[df["Daily_Usage_Hours"] >= 5]

print(high_usage)

       Student_ID  Age             Gender Academic_Level Primary_Platform  \
0     STU_2024000   19             Female  Undergraduate         Snapchat
2     STU_2024002   17             Female    High School           TikTok
3     STU_2024003   16             Female    High School          YouTube
5     STU_2024005   16               Male    High School           TikTok
6     STU_2024006   20               Male  Undergraduate           TikTok
...           ...  ...                ...            ...              ...
4487  STU_2028487   17  Prefer not to say    High School        Instagram
4491  STU_2028491   18             Female    High School          YouTube
4494  STU_2028494   16               Male    High School          YouTube
4495  STU_2028495   16               Male    High School          YouTube
4497  STU_2028497   19               Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone
2                  10.9                  1.7  Smartphone
3                   6.0                  2.3      Tablet
5                   6.2                  1.6  Smartphone
6                   5.6                  1.8  Smartphone
...                 ...                  ...         ...
4487                8.8                  2.5  Smartphone
4491                9.7                  1.9  Smartphone
4494                5.2                  1.6  Smartphone
4495                5.8                  1.2  Smartphone
4497                7.7                  1.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
0                      5.9                    2              True
2                      5.2                    1              True
3                      7.6                    4              True
5                      5.9                    1             False
6                      8.3                    3             False
...                    ...                  ...               ...
4487                   6.2                    1              True
4491                   4.2                    1              True
4494                   5.7                    3              True
4495                   7.8                    3              True
4497                   6.0                    2              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
0                         Always                    20.0                   73
2                     Frequently                    18.0                   70
3                      Sometimes                    15.0                   82
5                         Rarely                    10.0                   66
6                      Sometimes                    10.0                   88
...                          ...                     ...                  ...
4487                  Frequently                    21.0                   68
4491                   Sometimes                    21.0                   63
4494                   Sometimes                    24.0                   77
4495                   Sometimes                    11.0                   79
4497                  Frequently                    13.0                   73

      Academic_Performance_GPA Overall_Impact
0                         2.73        Neutral
2                         3.00        Neutral
3                         3.42     Beneficial
5                         3.21     Beneficial
6                         3.72     Beneficial
...                        ...            ...
4487                      3.50     Beneficial
4491                      2.73        Neutral
4494                      3.31        Neutral
4495                      2.85     Beneficial
4497                      3.16     Beneficial

[2058 rows x 16 columns]

In [ ]:
import pandas as pd

In [ ]:
#Adding a New column:
df = pd.read_csv("/Social_media_impact_on_life.csv")
df["country"] = "Pakistan"
print(df.head())

    Student_ID  Age  Gender Academic_Level Primary_Platform  \
0  STU_2024000   19  Female  Undergraduate         Snapchat
1  STU_2024001   19  Female  Undergraduate        Instagram
2  STU_2024002   17  Female    High School           TikTok
3  STU_2024003   16  Female    High School          YouTube
4  STU_2024004   17    Male    High School         LinkedIn

   Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  Sleep_Duration_Hours  \
0                7.5                  1.5  Smartphone                   5.9
1                4.6                  1.3  Smartphone                   7.9
2               10.9                  1.7  Smartphone                   5.2
3                6.0                  2.3      Tablet                   7.6
4                3.3                  2.6  Smartphone                   7.6

   Sleep_Quality_Score  Late_Night_Usage Social_Comparison_Frequency  \
0                    2              True                      Always
1                    3              True                   Sometimes
2                    1              True                  Frequently
3                    4              True                   Sometimes
4                    4              True                       Never

   Perceived_Stress_Score  Mental_Health_Index  Academic_Performance_GPA  \
0                    20.0                   73                      2.73
1                    17.0                   90                      3.21
2                    18.0                   70                      3.00
3                    15.0                   82                      3.42
4                    16.0                   84                      3.41

  Overall_Impact   country
0        Neutral  Pakistan
1     Beneficial  Pakistan
2        Neutral  Pakistan
3     Beneficial  Pakistan
4     Beneficial  Pakistan

In [ ]:
#Updating Values:
df.loc[2, ["Age","Primary_Platform"]] = [20,"youtube"]
df

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,20,Female,High School,youtube,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
#deleting rows and columns:
df = df.drop("Gender", axis= 1)
df = df.drop(4 , axis = 0 )
df.head()

,Student_ID,Age,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,20,High School,youtube,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
5,STU_2024005,16,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial

In [ ]:
# Handling missing value:
(df.isnull().sum())

Student_ID                     0
Age                            0
Academic_Level                 0
Primary_Platform               0
Daily_Usage_Hours              0
Weekend_Extra_Hours            0
Device_Type                    0
Sleep_Duration_Hours           0
Sleep_Quality_Score            0
Late_Night_Usage               0
Social_Comparison_Frequency    0
Perceived_Stress_Score         0
Mental_Health_Index            0
Academic_Performance_GPA       0
Overall_Impact                 0
dtype: int64

In [ ]:
df = df.dropna()
df

,Student_ID,Age,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,20,High School,youtube,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
5,STU_2024005,16,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
#Sorting data:
df = df.sort_values("Academic_Level", ascending= True)
df
df = df.sort_values("Academic_Level", ascending= False)
df

,Student_ID,Age,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
4399,STU_2028399,20,Undergraduate,Instagram,2.1,1.8,Smartphone,7.1,3,False,Sometimes,5.0,84,3.98,Beneficial
1254,STU_2025254,20,Undergraduate,TikTok,5.4,0.9,Smartphone,7.8,3,True,Sometimes,12.0,82,3.08,Beneficial
1263,STU_2025263,20,Undergraduate,YouTube,1.7,0.9,Smartphone,9.1,4,True,Sometimes,1.0,98,3.89,Beneficial
1244,STU_2025244,18,Undergraduate,TikTok,4.6,1.0,Smartphone,7.4,3,False,Frequently,6.0,92,3.78,Beneficial
1262,STU_2025262,18,Undergraduate,TikTok,2.5,0.9,Smartphone,7.6,3,True,Rarely,10.0,92,3.13,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2579,STU_2026579,16,High School,YouTube,3.4,2.0,Smartphone,7.4,3,True,Frequently,8.0,91,4.00,Beneficial
2580,STU_2026580,16,High School,TikTok,1.9,2.8,Smartphone,7.4,3,False,Always,10.0,88,3.97,Beneficial
477,STU_2024477,20,High School,Instagram,5.6,3.1,Smartphone,6.1,3,False,Sometimes,17.0,71,3.13,Beneficial
2581,STU_2026581,19,High School,Instagram,7.6,1.9,Smartphone,6.0,2,True,Sometimes,10.0,73,3.25,Beneficial
3637,STU_2027637,16,High School,YouTube,6.6,2.6,Smartphone,6.9,3,False,Sometimes,17.0,83,3.25,Beneficial

In [ ]:
#Aggregation and groupby:
result = df.groupby("Weekend_Extra_Hours")["Sleep_Duration_Hours"].mean()
print(result)

Weekend_Extra_Hours
0.0    6.391429
0.1    6.585714
0.2    6.700000
0.3    6.816000
0.4    6.905556
0.5    6.736585
0.6    6.852857
0.7    6.595238
0.8    6.568966
0.9    6.646078
1.0    6.709929
1.1    6.769231
1.2    6.680473
1.3    6.674468
1.4    6.674654
1.5    6.730702
1.6    6.684462
1.7    6.695726
1.8    6.553414
1.9    6.695902
2.0    6.637778
2.1    6.751984
2.2    6.707921
2.3    6.770166
2.4    6.800546
2.5    6.531008
2.6    6.752381
2.7    6.716822
2.8    6.757303
2.9    6.731646
3.0    6.672308
3.1    7.051429
3.2    6.809375
3.3    6.676190
3.4    6.447826
3.5    6.562500
3.6    7.233333
3.7    6.812500
3.8    6.450000
3.9    6.900000
4.0    7.850000
4.1    7.650000
4.5    6.700000
Name: Sleep_Duration_Hours, dtype: float64

In [ ]:
result = df.groupby("Weekend_Extra_Hours")["Sleep_Duration_Hours"].sum()
print(result)

Weekend_Extra_Hours
0.0     223.7
0.1      46.1
0.2     134.0
0.3     170.4
0.4     248.6
0.5     276.2
0.6     479.7
0.7     415.5
0.8     571.5
0.9     677.9
1.0     946.1
1.1    1056.0
1.2    1129.0
1.3    1254.8
1.4    1448.4
1.5    1534.6
1.6    1677.8
1.7    1566.8
1.8    1631.8
1.9    1633.8
2.0    1493.5
2.1    1701.5
2.2    1355.0
2.3    1225.4
2.4    1244.5
2.5     842.5
2.6     992.6
2.7     718.7
2.8     601.4
2.9     531.8
3.0     433.7
3.1     246.8
3.2     217.9
3.3     140.2
3.4     148.3
3.5      52.5
3.6      65.1
3.7      54.5
3.8      12.9
3.9      20.7
4.0      15.7
4.1      15.3
4.5       6.7
Name: Sleep_Duration_Hours, dtype: float64

In [ ]:
df[['Weekend_Extra_Hours','Sleep_Duration_Hours']]

      Weekend_Extra_Hours  Sleep_Duration_Hours
4399                  1.8                   7.1
1254                  0.9                   7.8
1263                  0.9                   9.1
1244                  1.0                   7.4
1262                  0.9                   7.6
...                   ...                   ...
2579                  2.0                   7.4
2580                  2.8                   7.4
477                   3.1                   6.1
2581                  1.9                   6.0
3637                  2.6                   6.9

[4368 rows x 2 columns]

In [ ]:
#Combining data frame
df1 = {"Platform" : ["Snapchat","TikTok","WhatsApp","Youtube"],
    "Daily_usage_hours" : [4,3,1,2]
}

df2 = {
    "Platform" : ["Instagram","Snapchat","Facebook","Whatsapp","Twitter"],
    "Daily_usage_hours" : [3,2,1,5,3]
}

df1 = pd.DataFrame(df1)
df2 = pd.DataFrame(df2)
final_result = pd.concat([df1,df2], ignore_index=True)
print(final_result)

    Platform  Daily_usage_hours
0   Snapchat                  4
1     TikTok                  3
2   WhatsApp                  1
3    Youtube                  2
4  Instagram                  3
5   Snapchat                  2
6   Facebook                  1
7   Whatsapp                  5
8    Twitter                  3

In [ ]:
#Student Practice Task:
#Task 1
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks": [70, 85, 60, 95, 45]
}

df = pd.DataFrame(data)

average = df["Marks"].mean()

maximum = df["Marks"].max()

minimum = df["Marks"].min()

total_students = df["Name"].count()

print("Average Marks:", average)
print("Maximum Marks:", maximum)
print("Minimum Marks:", minimum)
print("Total Students:", total_students)

Average Marks: 71.0
Maximum Marks: 95
Minimum Marks: 45
Total Students: 5

In [ ]:
#Task 2
data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks": [70, 85, 60, 95, 45]
}

df = pd.DataFrame(data)
print("Students whose marks are greater than or equal to 50:")
print(df[df["Marks"] >= 50])

print("\nStudents whose marks are less than 50:")
print(df[df["Marks"] < 50])

Students whose marks are greater than or equal to 50:
     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95

Students whose marks are less than 50:
   Name  Marks
4  Zain     45

In [ ]:
#Task 3
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Zain'],
    'Marks': [70, 85, 60, 95, 45],
    'City': ['Karachi', 'Lahore', 'Islamabad', 'Multan', 'Peshawar']
})

print("All Students:")
print(df)

karachi_students = df[df['City'] == 'Karachi']

print("\nStudents from Karachi:")
print(karachi_students)

All Students:
     Name  Marks       City
0     Ali     70    Karachi
1    Sara     85     Lahore
2   Ahmed     60  Islamabad
3  Ayesha     95     Multan
4    Zain     45   Peshawar

Students from Karachi:
  Name  Marks     City
0  Ali     70  Karachi

In [ ]:
#Task 4:
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Zain'],
    'Course': ['AI', 'Web', 'AI', 'Web', 'AI'],
    'Marks': [70, 85, 60, 95, 80]
})

print("All Students:")
print(df)

average_marks = df.groupby('Course')['Marks'].mean()

print("\nAverage Marks of Each Course:")
print(average_marks)

All Students:
     Name Course  Marks
0     Ali     AI     70
1    Sara    Web     85
2   Ahmed     AI     60
3  Ayesha    Web     95
4    Zain     AI     80

Average Marks of Each Course:
Course
AI     70.0
Web    90.0
Name: Marks, dtype: float64

In [ ]:
#Task 5:
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Zain'],
    'Marks': [80, None, 70, None, 90]
})

print("Number of missing values:")
print(df['Marks'].isnull().sum())

average = df['Marks'].mean()

df['Marks'] = df['Marks'].fillna(average)

print("\nCleaned DataFrame:")
print(df)

Number of missing values:
2

Cleaned DataFrame:
     Name  Marks
0     Ali   80.0
1    Sara   80.0
2   Ahmed   70.0
3  Ayesha   80.0
4    Zain   90.0